name: Async Federated Learning CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Lint with black
        run: |
          pip install black flake8
          black --check federated/ main.py || true
      
      - name: Run unit tests
        run: |
          pytest federated/tests/ -v --tb=short
      
  smoke-demo:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Run smoke demo
        run: |
          python main.py --config config.yaml --demo --seed 42
        timeout-minutes: 10
      
      - name: Check artifacts
        run: |
          ls -la runs/exp1/
          test -f runs/exp1/metrics.jsonl || echo "Warning: metrics.jsonl not found"
          test -f runs/exp1/experiment_metadata.json || echo "Warning: metadata not found"
      
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: smoke-demo-artifacts
          path: runs/
